private-nextflu: try to set bundle path via envvar
Trying to avoid error in test run https://github.com/joverlee521/nextstrain-testing/actions/runs/6115907081/job/16600262613
```
ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.2/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```